Repository Snazzah/slash-create, pull requests merged in 2021-07, with the labels that each got.

#71 feat: Select Menu Component
  docs/examples/components.md
  src/constants.ts
  src/index.ts
  src/structures/interfaces/componentContext.ts
  test/__util__/constants.ts
  test/structures/interfaces/componentContext.ts
Labels: type: enhancement

#82 feat(server): Azure Functions implementation
  .github/workflows/test.yml
  README.md
  docs/examples/azure.md
  docs/index.yml
  src/index.ts
  src/servers/azure.ts
Labels: scope: servers, semver: minor, type: enhancement

#84 Component callback rework
  src/creator.ts
  src/structures/interfaces/context.ts
  src/structures/interfaces/messageInteraction.ts
Labels: scope: components, semver: minor, type: enhancement

#87 Document local debugging tutorials (Az Functions, Webservers)
  docs/examples/azure.md
  docs/examples/webserver.js
  docs/examples/webserver.md
  docs/index.yml
Labels: type: documentation

#86 feat(types): add option type number
  src/constants.ts
Labels: scope: types, semver: minor, type: enhancement
