Repository Snazzah/slash-create, pull requests merged in 2021-11, with the labels that each got.

#175 Add `min_value` and `max_value` types to integer/number options
  src/constants.ts
Labels: type: enhancement, semver: patch

#158 feat: Add member avatar endpoint with related methods
  src/constants.ts
  src/structures/interfaces/autocompleteContext.ts
  src/structures/interfaces/commandContext.ts
  src/structures/interfaces/messageInteraction.ts
  src/structures/member.ts
  src/structures/resolvedMember.ts
Labels: type: enhancement, semver: minor, scope: types

#188 feat: add wildcard components
  src/creator.ts
  src/structures/interfaces/messageInteraction.ts
Labels: type: enhancement, semver: minor, scope: components
