Repository Snazzah/slash-create, pull requests merged in 2022-02, with the labels that each got.

#217 feat: add attachments to interactions
  src/constants.ts
  src/structures/interfaces/commandContext.ts
Labels: semver: minor, scope: components, scope: interactions

#245 feat(creator): Add rawRequest event
  src/constants.ts
  src/creator.ts
Labels: type: enhancement, semver: minor

#244 feat: Modal Interactions
  docs/examples/command.md
  src/command.ts
  src/constants.ts
  src/creator.ts
  src/index.ts
  src/structures/interfaces/commandContext.ts
  src/structures/interfaces/componentContext.ts
  src/structures/interfaces/messageInteraction.ts
  src/structures/interfaces/modalInteractionContext.ts
  src/structures/interfaces/modalSendableContext.ts
  src/util.ts
  test/__util__/constants.ts
  test/index.ts
  test/structures/interfaces/modalInteractionContext.ts
  test/structures/interfaces/modalSendableContext.ts
Labels: type: enhancement, semver: minor, scope: types, scope: components, scope: interactions

#246 chore(docs): Document the Lambda behaviour with defer/followUp
  docs/examples/lambda.md
Labels: type: documentation
